version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_PORT: ${NODE_PORT}
        NODE_VER: ${NODE_VER}
    container_name: react-menu-api
    image: react-menu-api
    environment:
      VIRTUAL_HOST: api.react-menu.local
      VIRTUAL_PORT: ${NODE_PORT}
      NODE_ENV: docker
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "88:3000"
#    networks:
#      - dev
    command: sh -c '
      npm i
      &&
      npm run build:all
      &&
      npm run start:dev
      '

  swagger:
    image: swaggerapi/swagger-ui
    container_name: react-menu-swagger
    environment:
      SWAGGER_JSON: /swagger/swagger.json
      VIRTUAL_HOST: swagger.react-menu.local
      VIRTUAL_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./api/dist:/swagger
#    networks:
#      - dev

#networks:
#  dev:
#    external:
#      name: dev
